spring:
  application:
    name: card-service

  datasource:
    url: jdbc:postgresql://localhost:5433/card_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"

server:
  port: 8082

feign:
  client:
    config:
      url: localhost:8081/api/v1
